"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {AlertCircle,Check,ChevronDown,Clapperboard,Download,Film,Loader2,Mic2,Pause,RotateCcw,Sparkles,WandSparkles} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Progress} from "@/components/ui/progress";
import {Badge} from "@/components/ui/badge";
import {Alert,AlertDescription,AlertTitle} from "@/components/ui/alert";
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from "@/components/ui/accordion";

type Shot={id:number;title:string;seconds:number;prompt:string;dialogue:string;status:"waiting"|"queued"|"rendering"|"ready"|"failed";requestId?:string;statusUrl?:string;responseUrl?:string;videoUrl?:string;error?:string};
type Plan={title:string;logline:string;style:string;characterBible:string;narration:string;shots:Shot[]};
type Stage="idea"|"planning"|"review"|"rendering"|"merging"|"narrating"|"complete"|"error";
type RenderMode="draft"|"standard"|"pro";
const MODE_INFO={draft:{label:"Draft · no audio",rate:.084,note:"Lowest-cost preview"},standard:{label:"Standard · native audio",rate:.126,note:"Balanced quality and cost"},pro:{label:"Cinema Pro · native audio",rate:.168,note:"Highest-quality final render"}} as const;

const examples=[
 "A retired astronaut discovers a tiny rocket growing in her garden. Make it emotional, hopeful and cinematic.",
 "A detective follows a red umbrella through rainy Mumbai and uncovers a surprising family secret.",
 "Two school friends enter a hidden library where unfinished stories come alive after midnight."
];

const stageCopy:Record<Stage,string>={
 idea:"Describe your movie",planning:"Writing screenplay",review:"Review the shot plan",rendering:"Generating cinematic shots",merging:"Assembling your movie",narrating:"Recording the performance",complete:"Your movie is ready",error:"Production stopped"
};

export default function Home(){
 const[idea,setIdea]=useState(""),[characters,setCharacters]=useState(""),[style,setStyle]=useState("Cinematic realism"),[format,setFormat]=useState("16:9"),[length,setLength]=useState("30"),[stage,setStage]=useState<Stage>("idea"),[plan,setPlan]=useState<Plan|null>(null),[movieUrl,setMovieUrl]=useState(""),[error,setError]=useState(""),[configured,setConfigured]=useState<boolean|null>(null),[renderMode,setRenderMode]=useState<RenderMode>("draft"),[outputMode,setOutputMode]=useState("narrated"),[voice,setVoice]=useState("american-woman"),[worldName,setWorldName]=useState(""),[ethnicity,setEthnicity]=useState(""),[age,setAge]=useState(""),[bodyType,setBodyType]=useState(""),[appearance,setAppearance]=useState(""),[characterAccent,setCharacterAccent]=useState(""),[ending,setEnding]=useState("Hopeful");
 const stop=useRef(false);
 useEffect(()=>{fetch("/api/movie/config").then(r=>r.json()).then(x=>setConfigured(Boolean(x.configured))).catch(()=>setConfigured(false));return()=>{stop.current=true}},[]);
 useEffect(()=>{try{const cast=JSON.parse(localStorage.getItem("fableloop-story-world")||"null");if(cast){setWorldName(cast.worldName||"");setCharacters(cast.characters||"");setEthnicity(cast.ethnicity||"");setAge(cast.age||"");setBodyType(cast.bodyType||"");setAppearance(cast.appearance||"");setCharacterAccent(cast.characterAccent||"")}}catch{}},[]);
 useEffect(()=>{try{const saved=localStorage.getItem("fableloop-production-v23");if(saved){const value=JSON.parse(saved);if(value?.plan){setPlan(value.plan);setIdea(value.idea||"");setCharacters(value.characters||"");setStyle(value.style||"Cinematic realism");setFormat(value.format||"16:9");setLength(value.length||"30");setRenderMode(value.renderMode||"draft");setOutputMode(value.outputMode||"narrated");setVoice(value.voice||"american-woman");setMovieUrl(value.movieUrl||"");setStage(value.movieUrl?"complete":"review")}}}catch{}},[]);
 useEffect(()=>{if(plan)try{localStorage.setItem("fableloop-production-v23",JSON.stringify({plan,idea,characters,style,format,length,renderMode,outputMode,voice,movieUrl}))}catch{}},[plan,idea,characters,style,format,length,renderMode,outputMode,voice,movieUrl]);
 const ready=plan?.shots.filter(s=>s.status==="ready").length||0,total=plan?.shots.length||0;
 const progress=stage==="planning"?8:stage==="review"?15:stage==="rendering"?(15+(ready/Math.max(total,1))*72):stage==="merging"?92:stage==="narrating"?97:stage==="complete"?100:0;
 const cost=useMemo(()=>{const seconds=Number(length);return{low:(seconds*.084).toFixed(2),high:(seconds*.168).toFixed(2)}},[length]);

 async function planMovie(){
  if(idea.trim().length<12){setError("Give FableLoop a little more detail about the movie.");return}
  setError("");setStage("planning");setMovieUrl("");
  const casting=[worldName&&`Story world: ${worldName}`,ethnicity&&`Ethnicity or cultural background: ${ethnicity}`,age&&`Age: ${age}`,bodyType&&`Body type: ${bodyType}`,appearance&&`Appearance, mobility and wardrobe locks: ${appearance}`,characterAccent&&`Speaking accent: ${characterAccent}`].filter(Boolean).join(". ");
  try{localStorage.setItem("fableloop-story-world",JSON.stringify({worldName,characters,ethnicity,age,bodyType,appearance,characterAccent}))}catch{}
  try{const r=await fetch("/api/movie/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea,characters,casting,ending,outputMode,narratorVoice:voice,style,format,length:Number(length)})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not plan the movie.");setPlan(data);setStage("review")}catch(e){setError(e instanceof Error?e.message:"Could not plan the movie.");setStage("error")}
 }
 function updateShot(id:number,patch:Partial<Shot>){setPlan(p=>p?{...p,shots:p.shots.map(s=>s.id===id?{...s,...patch}:s)}:p)}
 async function render(){
  if(!plan)return;if(!configured){setError("Add FAL_KEY in Vercel Environment Variables before rendering a real movie.");setStage("error");return}
  const unfinished=plan.shots.filter(s=>s.status!=="ready");
  if(!unfinished.length){await mergeMovie(plan.shots.map(s=>s.videoUrl).filter(Boolean) as string[]);return}
  stop.current=false;setError("");setStage("rendering");
  const completed=new Map(plan.shots.filter(s=>s.videoUrl).map(s=>[s.id,s.videoUrl as string]));
  for(const shot of unfinished){
   try{
    updateShot(shot.id,{status:"queued"});
    const submit=await fetch("/api/movie/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:shot.prompt,dialogue:shot.dialogue,seconds:shot.seconds,format,mode:renderMode,outputMode})});
    const job=await submit.json();if(!submit.ok)throw new Error(job.error||"Shot submission failed.");
    if(!job.requestId||!job.statusUrl||!job.responseUrl)throw new Error("Provider returned an incomplete render job.");
    updateShot(shot.id,{status:"rendering",requestId:job.requestId,statusUrl:job.statusUrl,responseUrl:job.responseUrl});
    let done=false,renderedUrl="";
    for(let attempt=0;attempt<120&&!done;attempt++){
     if(stop.current)return;
     await new Promise(r=>setTimeout(r,5000));
     const query=new URLSearchParams({requestId:job.requestId,statusUrl:job.statusUrl,responseUrl:job.responseUrl});
     const status=await fetch(`/api/movie/status?${query.toString()}`);
     const data=await status.json();if(!status.ok)throw new Error(data.error||"Render status failed.");
     if(data.status==="COMPLETED"){if(!data.videoUrl)throw new Error("Provider completed without a video.");renderedUrl=data.videoUrl;updateShot(shot.id,{status:"ready",videoUrl:data.videoUrl,error:undefined});done=true}
     else if(data.status==="FAILED")throw new Error(data.error||"Provider could not render this shot.");
    }
    if(!done)throw new Error("This scene exceeded the render time limit.");
    completed.set(shot.id,renderedUrl);
   }catch(e){updateShot(shot.id,{status:"failed",error:e instanceof Error?e.message:"Shot failed"});setError(`“${shot.title}” failed. Completed shots are safe. You can retry only this unfinished shot.`);setStage("error");return}
  }
  await mergeMovie(plan.shots.map(s=>completed.get(s.id)||s.videoUrl).filter(Boolean) as string[]);
 }
 async function mergeMovie(completed:string[]){
  if(!plan||completed.length!==plan.shots.length){setError("Render every shot before assembling the movie.");setStage("review");return}
  setError("");setStage("merging");
  try{
   const r=await fetch("/api/movie/merge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videoUrls:completed})});const job=await r.json();if(!r.ok)throw new Error(job.error||"Could not assemble the movie.");
   if(!job.requestId||!job.statusUrl||!job.responseUrl)throw new Error("Provider returned an incomplete assembly job.");
   for(let attempt=0;attempt<80;attempt++){await new Promise(x=>setTimeout(x,3000));const query=new URLSearchParams({requestId:job.requestId,statusUrl:job.statusUrl,responseUrl:job.responseUrl});const s=await fetch(`/api/movie/status?${query.toString()}`);const data=await s.json();if(!s.ok)throw new Error(data.error||"Could not read movie assembly status.");if(data.status==="COMPLETED"){if(!data.videoUrl)throw new Error("Movie merge finished without a file.");if(outputMode==="narrated"){await addNarration(data.videoUrl);return}setMovieUrl(data.videoUrl);setStage("complete");return}if(data.status==="FAILED")throw new Error(data.error||"Movie assembly failed.")}
   throw new Error("Movie assembly exceeded the time limit.");
  }catch(e){setError(e instanceof Error?e.message:"Movie assembly failed.");setStage("error")}
 }
 async function addNarration(assembledVideo:string){
  if(!plan?.narration)throw new Error("The screenplay has no narration track.");
  setStage("narrating");
  const submit=await fetch("/api/movie/narrate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:plan.narration,voice})}),voiceJob=await submit.json();if(!submit.ok)throw new Error(voiceJob.error||"Narration could not start.");
  let audioUrl="";
  for(let attempt=0;attempt<60;attempt++){await new Promise(x=>setTimeout(x,2000));const query=new URLSearchParams({requestId:voiceJob.requestId,statusUrl:voiceJob.statusUrl,responseUrl:voiceJob.responseUrl});const s=await fetch(`/api/movie/status?${query.toString()}`),data=await s.json();if(!s.ok)throw new Error(data.error||"Could not read narration status.");if(data.status==="COMPLETED"){audioUrl=data.audioUrl||"";break}if(data.status==="FAILED")throw new Error(data.error||"Narration failed.")}
  if(!audioUrl)throw new Error("Narration finished without an audio file.");
  const mix=await fetch("/api/movie/mix",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videoUrl:assembledVideo,audioUrl})}),mixJob=await mix.json();if(!mix.ok)throw new Error(mixJob.error||"Could not mix narration into the movie.");
  for(let attempt=0;attempt<60;attempt++){await new Promise(x=>setTimeout(x,2000));const query=new URLSearchParams({requestId:mixJob.requestId,statusUrl:mixJob.statusUrl,responseUrl:mixJob.responseUrl});const s=await fetch(`/api/movie/status?${query.toString()}`),data=await s.json();if(!s.ok)throw new Error(data.error||"Could not read final mix status.");if(data.status==="COMPLETED"){if(!data.videoUrl)throw new Error("Final mix completed without a movie.");setMovieUrl(data.videoUrl);setStage("complete");return}if(data.status==="FAILED")throw new Error(data.error||"Final narration mix failed.")}
  throw new Error("Narration mix exceeded the time limit.");
 }
 function reset(){stop.current=true;setPlan(null);setMovieUrl("");setError("");setStage("idea");try{localStorage.removeItem("fableloop-production-v23")}catch{}}

 return <main className="min-h-screen bg-[#0b0c11] text-[#f5f3ef]">
  <header className="border-b border-white/10 bg-[#0b0c11]/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 lg:px-8"><button onClick={reset} className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#ff5d45]"><Clapperboard size={19}/></span><span className="text-xl font-bold tracking-[-.04em]">FableLoop <em className="font-normal text-white/45">Cinema</em></span></button><div className="flex items-center gap-3"><span className={`size-2 rounded-full ${configured?"bg-emerald-400":"bg-amber-400"}`}/><span className="hidden text-xs text-white/55 sm:inline">{configured?"Movie engine connected":"Setup mode"}</span><Badge className="border-white/10 bg-white/5 text-white hover:bg-white/5">v2.4</Badge></div></div></header>
  <div className="mx-auto max-w-6xl">
   <section className="min-w-0 px-5 py-8 sm:px-8 lg:py-12">
    <div className="mx-auto max-w-5xl">
     <div className="mb-8"><div className="mb-7 flex items-center gap-2">{["Idea","Preview","Movie"].map((x,i)=>{const active=stage==="idea"?0:(stage==="planning"||stage==="review")?1:2;return <div key={x} className={`rounded-full px-4 py-2 text-xs font-bold ${i===active?"bg-white text-black":i<active?"bg-[#ff5d45] text-white":"bg-white/5 text-white/30"}`}>{i+1}. {x}</div>})}</div><div className="flex items-start justify-between gap-6"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-[#ff765f]">AI MOVIE STUDIO</p><h1 className="text-4xl font-bold leading-none tracking-[-.05em] sm:text-5xl">{stageCopy[stage]}</h1></div>{stage!=="idea"&&<Button variant="outline" onClick={reset} className="border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white"><RotateCcw/>New movie</Button>}</div></div>
     {error&&<Alert className="mb-6 border-red-400/25 bg-red-400/10 text-red-100"><AlertCircle/><AlertTitle>Production message</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
     {stage==="idea"&&<IdeaForm idea={idea} setIdea={setIdea} characters={characters} setCharacters={setCharacters} style={style} setStyle={setStyle} format={format} setFormat={setFormat} length={length} setLength={setLength} cost={cost} configured={configured} onPlan={planMovie} outputMode={outputMode} setOutputMode={setOutputMode} voice={voice} setVoice={setVoice} worldName={worldName} setWorldName={setWorldName} ethnicity={ethnicity} setEthnicity={setEthnicity} age={age} setAge={setAge} bodyType={bodyType} setBodyType={setBodyType} appearance={appearance} setAppearance={setAppearance} characterAccent={characterAccent} setCharacterAccent={setCharacterAccent} ending={ending} setEnding={setEnding}/>}
     {stage==="planning"&&<Loading title="Writing your screenplay" text="Building the cast bible, dialogue, action, camera direction and connected shot plan."/>}
     {(stage==="review"||stage==="rendering"||stage==="merging"||stage==="narrating"||stage==="error")&&plan&&<Production plan={plan} setPlan={setPlan} stage={stage} progress={progress} ready={ready} total={total} onRender={render} renderMode={renderMode} setRenderMode={setRenderMode} outputMode={outputMode} voice={voice}/>}
     {stage==="complete"&&plan&&movieUrl&&<Finished plan={plan} movieUrl={movieUrl} onReset={reset}/>}
    </div>
   </section>
  </div>
 </main>
}

function IdeaForm(p:{idea:string;setIdea:(x:string)=>void;characters:string;setCharacters:(x:string)=>void;style:string;setStyle:(x:string)=>void;format:string;setFormat:(x:string)=>void;length:string;setLength:(x:string)=>void;cost:{low:string;high:string};configured:boolean|null;onPlan:()=>void;outputMode:string;setOutputMode:(x:string)=>void;voice:string;setVoice:(x:string)=>void;worldName:string;setWorldName:(x:string)=>void;ethnicity:string;setEthnicity:(x:string)=>void;age:string;setAge:(x:string)=>void;bodyType:string;setBodyType:(x:string)=>void;appearance:string;setAppearance:(x:string)=>void;characterAccent:string;setCharacterAccent:(x:string)=>void;ending:string;setEnding:(x:string)=>void}){
 return <div className="grid gap-6 lg:grid-cols-[1fr_330px]"><div className="overflow-hidden rounded-[26px] border border-white/10 bg-[#13151d] shadow-2xl"><div className="p-6 sm:p-8"><Label className="mb-3 block text-sm font-bold">Tell us the movie you imagine</Label><Textarea value={p.idea} onChange={e=>p.setIdea(e.target.value)} placeholder="A detective follows a red umbrella through rainy Mumbai and uncovers a surprising family secret…" className="min-h-40 resize-none rounded-2xl border-white/10 bg-[#0d0f15] p-5 text-base leading-7 text-white placeholder:text-white/25"/><div className="mt-3 flex flex-wrap gap-2">{examples.map((x,i)=><button key={x} onClick={()=>p.setIdea(x)} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/45 hover:border-[#ff765f] hover:text-white">Try concept {i+1}</button>)}</div></div><Accordion type="single" collapsible className="border-t border-white/10 px-6 sm:px-8"><AccordionItem value="cast" className="border-0"><AccordionTrigger className="hover:no-underline"><div className="text-left"><span className="font-bold">Customize cast</span><p className="mt-1 text-xs font-normal text-white/35">Optional: ethnicity, age, body type, accent, mobility and wardrobe.</p></div></AccordionTrigger><AccordionContent><div className="grid gap-4 pb-6 sm:grid-cols-2"><Field label="Story world name" value={p.worldName} set={p.setWorldName} placeholder="The Starlight Garden"/><Field label="Character name and role" value={p.characters} set={p.setCharacters} placeholder="Maya, determined detective"/><Field label="Ethnicity / cultural background" value={p.ethnicity} set={p.setEthnicity} placeholder="Indian American, Punjabi heritage"/><Field label="Age or life stage" value={p.age} set={p.setAge} placeholder="68 years old"/><Field label="Body type" value={p.bodyType} set={p.setBodyType} placeholder="Short, broad-shouldered, plus-size…"/><Field label="Character speaking accent" value={p.characterAccent} set={p.setCharacterAccent} placeholder="Texas, Indian English, British…"/></div><div className="pb-6"><Label className="mb-2 block text-xs text-white/45">Appearance, disability, mobility, hair and clothing details</Label><Textarea value={p.appearance} onChange={e=>p.setAppearance(e.target.value)} placeholder="Silver-gray curls, hazel eyes, uses a decorated walking cane, cream cardigan…" className="min-h-20 border-white/10 bg-[#0d0f15] text-white"/></div></AccordionContent></AccordionItem></Accordion><div className="flex flex-col justify-between gap-4 border-t border-white/10 bg-white/[.025] p-6 sm:flex-row sm:items-center sm:p-8"><p className="max-w-md text-xs leading-5 text-white/40">Preview your story and cast before creating the complete movie.</p><Button onClick={p.onPlan} className="h-12 rounded-xl bg-[#ff5d45] px-6 font-bold hover:bg-[#e84d37]"><WandSparkles/>Preview my movie</Button></div></div>
 <aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-[#13151d] p-5"><p className="mb-4 text-xs font-bold uppercase tracking-wider text-white/35">Movie direction</p><Pick label="Output" value={p.outputMode} set={p.setOutputMode} values={["narrated","dialogue"]}/>{p.outputMode==="narrated"&&<div className="mt-4"><Pick label="Narrator voice and language" value={p.voice} set={p.setVoice} values={["american-woman","american-man","british-woman","british-man","hindi-woman","hindi-man","spanish-woman","spanish-man"]}/></div>}<div className="mt-4"><Pick label="Visual style" value={p.style} set={p.setStyle} values={["Cinematic realism","3D animated film","Stylized graphic novel","Warm family cinema","Dark atmospheric thriller"]}/></div><div className="mt-4"><Pick label="Ending tone" value={p.ending} set={p.setEnding} values={["Hopeful","Joyful","Surprising","Bittersweet","Mysterious","Open ending"]}/></div><div className="mt-4 grid grid-cols-2 gap-3"><Pick label="Format" value={p.format} set={p.setFormat} values={["16:9","9:16"]}/><Pick label="Length" value={p.length} set={p.setLength} values={["15","30","45","60"]} suffix=" sec"/></div></div><div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.06] p-5"><div className="flex items-center gap-2 text-emerald-200"><Mic2 size={17}/><b className="text-sm">{p.outputMode==="narrated"?"Continuous narration":"Acted character dialogue"}</b></div><p className="mt-2 text-xs leading-5 text-white/45">{p.outputMode==="narrated"?"One voice performance is recorded after the film is assembled—far cheaper than native audio in every clip.":"Characters speak inside scenes with native audio and lip-sync."}</p></div><div className="rounded-2xl border border-white/10 bg-[#13151d] p-5"><div className="flex items-center justify-between"><span className="text-sm text-white/60">Estimated visual cost</span><b>${p.cost.low}–${p.cost.high}</b></div><p className="mt-2 text-xs leading-5 text-white/35">Narration is approximately $0.02 per 1,000 characters. Visual retries remain the largest cost.</p></div>{p.configured===false&&<Alert className="border-amber-400/20 bg-amber-400/10 text-amber-100"><AlertCircle/><AlertTitle>Setup required</AlertTitle><AlertDescription>Add FAL_KEY in Vercel before rendering. Planning still works.</AlertDescription></Alert>}</aside></div>
}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(x:string)=>void;placeholder:string}){return <div><Label className="mb-2 block text-xs text-white/45">{label}</Label><Input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="border-white/10 bg-[#0d0f15] text-white"/></div>}
function Pick({label,value,set,values,suffix=""}:{label:string;value:string;set:(x:string)=>void;values:string[];suffix?:string}){return <div><Label className="mb-2 block text-xs text-white/45">{label}</Label><Select value={value} onValueChange={x=>x&&set(x)}><SelectTrigger className="w-full border-white/10 bg-[#0d0f15] text-white"><SelectValue/></SelectTrigger><SelectContent>{values.map(x=><SelectItem key={x} value={x}>{x}{suffix}</SelectItem>)}</SelectContent></Select></div>}
function Loading({title,text}:{title:string;text:string}){return <div className="rounded-[26px] border border-white/10 bg-[#13151d] p-12 text-center sm:p-20"><span className="mx-auto mb-6 grid size-16 place-items-center rounded-full bg-[#ff5d45]/15 text-[#ff765f]"><Loader2 className="animate-spin" size={30}/></span><h2 className="text-2xl font-bold">{title}</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-white/45">{text}</p></div>}
function Production({plan,setPlan,stage,progress,ready,total,onRender,renderMode,setRenderMode,outputMode,voice}:{plan:Plan;setPlan:(p:Plan)=>void;stage:Stage;progress:number;ready:number;total:number;onRender:()=>void;renderMode:RenderMode;setRenderMode:(m:RenderMode)=>void;outputMode:string;voice:string}){
 const editable=stage==="review"||stage==="error",remaining=plan.shots.filter(s=>s.status!=="ready"),remainingSeconds=remaining.reduce((n,s)=>n+s.seconds,0),rate=outputMode==="narrated"?(renderMode==="pro"?.112:.084):MODE_INFO[renderMode].rate,totalCost=remainingSeconds*rate,busy=!editable;
 return <div className="space-y-5"><div className="overflow-hidden rounded-[28px] border border-white/10 bg-[#13151d]"><div className="p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><Badge className="mb-4 bg-[#ff5d45]/15 text-[#ff8978] hover:bg-[#ff5d45]/15">{plan.style}</Badge><h2 className="text-3xl font-bold tracking-tight">{plan.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/50">{plan.logline}</p></div><div className="grid min-w-48 grid-cols-2 gap-2 text-center"><div className="rounded-xl bg-white/5 p-3"><p className="text-[11px] text-white/35">Movie length</p><b>{plan.shots.reduce((n,s)=>n+s.seconds,0)} sec</b></div><div className="rounded-xl bg-white/5 p-3"><p className="text-[11px] text-white/35">Estimated cost</p><b>${totalCost.toFixed(2)}</b></div></div></div></div>{busy?<div className="border-t border-white/10 bg-[#0d0f15] p-6 sm:p-8"><div className="mb-3 flex justify-between"><b>{stage==="rendering"?`Creating scene ${Math.min(ready+1,total)} of ${total}`:stageCopy[stage]}</b><span>{Math.round(progress)}%</span></div><Progress value={progress} className="h-2"/><p className="mt-3 text-sm text-white/40">Your complete movie is being created automatically. Finished scenes are safely saved.</p></div>:<div className="flex flex-col items-center border-t border-white/10 bg-white/[.025] p-6 text-center sm:p-8"><Button onClick={onRender} className="h-14 rounded-xl bg-[#ff5d45] px-9 text-base font-bold hover:bg-[#e84d37]"><Clapperboard/>Create complete movie · ${totalCost.toFixed(2)}</Button><p className="mt-3 text-xs text-white/35">One click creates every remaining scene, joins them, and adds the final voice track.</p></div>}</div>
 <Accordion type="single" collapsible className="rounded-2xl border border-white/10 bg-[#13151d] px-5"><AccordionItem value="advanced" className="border-0"><AccordionTrigger className="hover:no-underline"><div className="text-left"><b>Advanced production</b><p className="mt-1 text-xs font-normal text-white/35">Optional: inspect scenes, edit prompts, narration, cast continuity and quality.</p></div></AccordionTrigger><AccordionContent><div className="grid gap-6 pb-5 lg:grid-cols-[1fr_260px]"><div className="space-y-4">{outputMode==="narrated"&&<div><Label className="mb-2 block text-xs text-white/45">Narration · {voice.replaceAll("-"," ")}</Label><Textarea value={plan.narration||""} disabled={!editable} onChange={e=>setPlan({...plan,narration:e.target.value})} className="min-h-28 border-white/10 bg-[#0d0f15] text-white"/></div>}<Accordion type="single" collapsible>{plan.shots.map((shot,i)=><AccordionItem key={shot.id} value={String(shot.id)}><AccordionTrigger><span className="flex items-center gap-3"><ShotStatus status={shot.status}/>Scene {i+1}: {shot.title}</span></AccordionTrigger><AccordionContent><Textarea value={shot.prompt} disabled={!editable} onChange={e=>setPlan({...plan,shots:plan.shots.map(s=>s.id===shot.id?{...s,prompt:e.target.value}:s)})} className="min-h-28 border-white/10 bg-[#0d0f15] text-white"/>{shot.videoUrl&&<video src={shot.videoUrl} controls className="mt-3 aspect-video w-full rounded-xl bg-black"/>}</AccordionContent></AccordionItem>)}</Accordion></div><div className="space-y-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-white/35">Character continuity</p><p className="text-sm leading-6 text-white/55">{plan.characterBible}</p></div><Pick label="Render quality" value={renderMode} set={x=>setRenderMode(x as RenderMode)} values={["draft","standard","pro"]}/><p className="text-xs text-white/35">{MODE_INFO[renderMode].label} · {MODE_INFO[renderMode].note}</p></div></div></AccordionContent></AccordionItem></Accordion></div>
}
function ShotStatus({status}:{status:Shot["status"]}){const map={waiting:["bg-white/5 text-white/35",Film],queued:["bg-amber-400/10 text-amber-300",Pause],rendering:["bg-blue-400/10 text-blue-300",Loader2],ready:["bg-emerald-400/10 text-emerald-300",Check],failed:["bg-red-400/10 text-red-300",AlertCircle]} as const;const[c,I]=map[status];return <span className={`grid size-10 shrink-0 place-items-center rounded-xl ${c}`}><I size={18} className={status==="rendering"?"animate-spin":""}/></span>}
function Finished({plan,movieUrl,onReset}:{plan:Plan;movieUrl:string;onReset:()=>void}){return <div className="overflow-hidden rounded-[28px] border border-white/10 bg-[#13151d]"><video src={movieUrl} controls autoPlay className="aspect-video w-full bg-black"/><div className="flex flex-col justify-between gap-5 p-6 sm:flex-row sm:items-center sm:p-8"><div><h2 className="text-2xl font-bold">{plan.title}</h2><p className="mt-2 text-sm text-white/45">All {plan.shots.length} shots assembled into one downloadable MP4.</p></div><div className="flex gap-3"><Button variant="outline" onClick={onReset} className="border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white"><Sparkles/>New movie</Button><Button asChild className="bg-[#ff5d45] hover:bg-[#e84d37]"><a href={movieUrl} download><Download/>Download MP4</a></Button></div></div></div>}
