import{NextRequest,NextResponse}from"next/server";
type Input={idea:string;characters?:string;style:string;format:string;length:number};
function fallback(x:Input){
 const count=Math.max(3,Math.min(12,Math.ceil(x.length/5))),bible=x.characters?.trim()||"Create one distinctive lead character. Preserve the identical face, age, hair, clothing colors and body proportions in every shot.";
 const beats=["A visually arresting opening establishes the world and protagonist","The protagonist notices an unexpected clue and chooses to follow it","The situation becomes more difficult and the emotional stakes rise","A surprising discovery changes the meaning of the journey","The protagonist acts decisively at the climax","A final cinematic image resolves the emotion without narration"];
 return{title:x.idea.split(/[.!?]/)[0].slice(0,60)||"Untitled FableLoop Movie",logline:x.idea,style:x.style,characterBible:bible,shots:Array.from({length:count},(_,i)=>({id:i+1,title:["Opening image","Inciting discovery","Rising action","Revelation","Climax","Final image"][Math.min(i,5)]||`Sequence ${i+1}`,seconds:Math.min(5,x.length-i*5),prompt:`${x.style}, ${x.format} cinematic frame. ${bible} Story: ${x.idea}. ${beats[Math.min(i,beats.length-1)]}. Shot ${i+1} of ${count}. Natural acting, meaningful character movement, cinematic lighting, coherent environment, professional composition, camera movement, native environmental audio and sound effects. No subtitles, no on-screen text, no narration.`,dialogue:"",status:"waiting"}))};
}
const SYSTEM=`You are a film director and screenwriter. Return only valid JSON. Convert a short concept into a coherent micro-movie made of connected 5-second shots. Output: {"title":string,"logline":string,"characterBible":string,"shots":[{"title":string,"prompt":string,"dialogue":string}]}. CharacterBible must give immutable face, age, hair, clothing and color details. Each prompt must repeat all relevant immutable character details, connect to the prior shot, specify physical action, emotion, environment, lighting, camera/lens movement, native ambience and effects. Dialogue must be short enough for five seconds and identify the speaker inside the prompt. Use dialogue selectively. Never use narration, captions, title cards, copyrighted characters, celebrities or living artists. The finished result must feel acted and cinematic, not like someone reading a story.`;
export async function POST(req:NextRequest){try{const x=await req.json() as Input;if(!x.idea||x.idea.trim().length<12||x.idea.length>1500)return NextResponse.json({error:"Provide a movie idea between 12 and 1,500 characters."},{status:400});const basic=fallback(x),key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json(basic);const count=basic.shots.length;const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4.1-mini",response_format:{type:"json_object"},temperature:.8,messages:[{role:"system",content:SYSTEM},{role:"user",content:`Concept: ${x.idea}\nCharacter request: ${x.characters||"Design the cast"}\nStyle: ${x.style}\nFormat: ${x.format}\nCreate exactly ${count} connected shots.`}]})});if(!r.ok)return NextResponse.json(basic);const data=await r.json(),made=JSON.parse(data.choices?.[0]?.message?.content||"{}");if(!Array.isArray(made.shots)||made.shots.length!==count)return NextResponse.json(basic);return NextResponse.json({title:made.title,logline:made.logline,style:x.style,characterBible:made.characterBible,shots:made.shots.map((s:{title:string;prompt:string;dialogue?:string},i:number)=>({id:i+1,title:s.title,seconds:basic.shots[i].seconds,prompt:`${x.style}. ${made.characterBible}. ${s.prompt} ${s.dialogue?`The character speaks exactly: “${s.dialogue}”. Accurate natural lip sync.`:""} No narration, subtitles, logos or text.`,dialogue:s.dialogue||"",status:"waiting"}))})}catch{return NextResponse.json({error:"The screenplay could not be created."},{status:500})}}
