"use client";

import { useEffect, useState } from "react";
import { BookOpen, ChevronLeft, ChevronRight, CirclePlay, Film, Library, Loader2, Mic2, Pause, Plus, RotateCcw, Sparkles, Users, Volume2, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";

type Character={name:string;role:string;look:string;trait:string;color:string};
type Choice={label:string;consequence:string};
type Scene={title:string;narration:string;dialogue?:string;character?:string;visual:string;choice?:Choice[]};
type Story={id:string;title:string;logline:string;genre:string;tone:string;characters:Character[];scenes:Scene[];createdAt:string};

const demo:Story={id:"demo",title:"The Library Beyond the Moon",logline:"A young mapmaker follows a glowing paper bird to a library where forgotten stories wait to be found.",genre:"Magical adventure",tone:"Wonder-filled",createdAt:new Date().toISOString(),characters:[{name:"Mira",role:"Young mapmaker",look:"Indigo coat, copper compass, dark curls",trait:"Brave and observant",color:"#7357ff"},{name:"Pip",role:"Paper bird",look:"Folded gold wings with ink-blue edges",trait:"Playful and loyal",color:"#eead3b"},{name:"The Keeper",role:"Guardian of stories",look:"Silver spectacles and a coat of moving letters",trait:"Gentle and mysterious",color:"#3ca98b"}],scenes:[{title:"A map with no ending",narration:"Mira had drawn every street in her city—except one. Each night, a silver path appeared on her map and vanished before sunrise.",dialogue:"Tonight, I am following it.",character:"Mira",visual:"Moonlit map room · silver ink · quiet anticipation"},{title:"The paper bird",narration:"At midnight, a golden paper bird unfolded itself from the map. It circled Mira's compass, then flew through the open window.",dialogue:"Wait for me!",character:"Mira",visual:"Rooftops under violet clouds · golden trail · swift motion"},{title:"The impossible door",narration:"The trail ended at a tiny blue door hidden in the clock tower. Behind it was a staircase rising into the stars.",dialogue:"Some doors only appear to people looking for the right story.",character:"The Keeper",visual:"Star staircase · enormous moon · luminous doorway"},{title:"A choice among stories",narration:"Beyond the moon stood a library without walls. One book whispered Mira's name. Another shook as if something inside needed help.",visual:"Infinite floating shelves · two radiant books · drifting letters",choice:[{label:"Open the book calling Mira",consequence:"Mira discovers a forgotten chapter from her own family."},{label:"Rescue the shaking book",consequence:"Mira releases a storm creature trapped between its pages."}]},{title:"The story chooses back",narration:"Mira understood at last: a map shows where a journey begins, but a choice decides where it leads.",dialogue:"Every story is a door. Choose with courage.",character:"The Keeper",visual:"Warm sunrise over the moon library · open book · hopeful glow"}]};
const ideas=["A shy girl discovers that her grandmother's recipes open doors to forgotten places.","Two brothers find a tiny lighthouse in their garden that signals ships from other worlds.","A funny mystery about a principal whose morning tea keeps disappearing."];
const savedStories=()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem("fableloop-stories")||"[]")}catch{return[]}};

export default function Home(){
 const[tab,setTab]=useState("create"),[idea,setIdea]=useState(""),[genre,setGenre]=useState("Magical adventure"),[tone,setTone]=useState("Wonder-filled"),[duration,setDuration]=useState("3 minutes"),[loading,setLoading]=useState(false),[story,setStory]=useState<Story|null>(null),[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[choice,setChoice]=useState<string|null>(null),[saved,setSaved]=useState<Story[]>([]),[notice,setNotice]=useState("");
 useEffect(()=>{const id=requestAnimationFrame(()=>setSaved(savedStories()));return()=>cancelAnimationFrame(id)},[]);useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 const scene=story?.scenes[index],character=story?.characters.find(c=>c.name===scene?.character);
 const persist=(list:Story[])=>{setSaved(list);localStorage.setItem("fableloop-stories",JSON.stringify(list))};
 async function create(){if(!idea.trim()){setNotice("Describe your story idea first.");return}setLoading(true);setNotice("");setIndex(0);setChoice(null);try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea,genre,tone,duration})});if(!r.ok)throw 0;const s=await r.json() as Story;setStory(s);setTab("watch");persist([s,...saved.filter(x=>x.id!==s.id)].slice(0,20))}catch{const s={...demo,id:`local-${Date.now()}`,title:idea.split(/[.!?]/)[0].slice(0,48)||demo.title,logline:idea,genre,tone,createdAt:new Date().toISOString()};setStory(s);setTab("watch");persist([s,...saved].slice(0,20));setNotice("Preview created in demo mode. Add an AI key after deployment for fully original stories.")}finally{setLoading(false)}}
 function narrate(){if(!scene||!("speechSynthesis"in window))return;if(playing){speechSynthesis.cancel();setPlaying(false);return}const u=new SpeechSynthesisUtterance(`${scene.narration} ${scene.dialogue||""}`);u.rate=.92;u.onend=()=>setPlaying(false);speechSynthesis.speak(u);setPlaying(true)}
 function move(n:number){speechSynthesis.cancel();setPlaying(false);if(story)setIndex(Math.max(0,Math.min(story.scenes.length-1,n)))}
 function open(s:Story){setStory(s);setIndex(0);setChoice(null);setTab("watch")}
 return <main className="min-h-screen text-[#25213a]">
  <header className="sticky top-0 z-30 border-b border-[#ddd7f0] bg-[#fbf9f5]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 lg:px-8"><button className="flex items-center gap-3" onClick={()=>setTab("create")}><span className="grid size-9 place-items-center rounded-xl bg-[#6246ea] text-white"><BookOpen size={19}/></span><b className="text-xl tracking-[-.04em]">FableLoop</b></button><div className="flex items-center gap-3 text-sm text-[#706a83]"><span className="hidden sm:inline">Imagine it. Enter it. Continue it.</span><Badge className="rounded-full bg-[#eeeafd] text-[#5d43d8] hover:bg-[#eeeafd]">MVP Studio</Badge></div></div></header>
  <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[230px_1fr]"><aside className="hidden min-h-[calc(100vh-4rem)] border-r border-[#e3deee] p-5 lg:block"><nav className="space-y-2">{[["create",WandSparkles,"Create story"],["watch",CirclePlay,"Story player"],["library",Library,"My worlds"]].map(([id,Icon,label])=><button key={id as string} onClick={()=>setTab(id as string)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold ${tab===id?"bg-[#ece7ff] text-[#563bd4]":"text-[#6f697f] hover:bg-white"}`}><Icon size={18}/>{label as string}{id==="library"&&saved.length>0?<span className="ml-auto rounded-full bg-white px-2 text-xs">{saved.length}</span>:null}</button>)}</nav><div className="mt-8 rounded-2xl border bg-white p-4"><div className="mb-2 flex items-center gap-2 text-sm font-bold"><Sparkles size={16} className="text-orange-500"/>Story memory</div><p className="text-xs leading-5 text-[#777083]">Characters and story worlds stay saved in this browser for the next episode.</p></div></aside>
  <section className="min-w-0 px-4 py-5 sm:px-7 lg:px-10 lg:py-9"><Tabs value={tab} onValueChange={setTab}><TabsList className="mb-6 grid w-full grid-cols-3 lg:hidden"><TabsTrigger value="create">Create</TabsTrigger><TabsTrigger value="watch">Watch</TabsTrigger><TabsTrigger value="library">Worlds</TabsTrigger></TabsList>
   <TabsContent value="create"><div className="mx-auto max-w-5xl"><div className="mb-8"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-[#6246ea]"><Sparkles size={17}/>NEW STORY</div><h1 className="max-w-3xl text-4xl font-bold leading-[1.04] tracking-[-.045em] sm:text-5xl">One idea becomes a world worth entering.</h1><p className="mt-4 max-w-2xl leading-7 text-[#726c80]">You do not need to write the story. Describe the spark; FableLoop builds its characters, narrative, scenes, narration and turning point.</p></div>
    <div className="overflow-hidden rounded-[26px] border bg-white shadow-[0_22px_70px_rgba(65,47,105,.10)]"><div className="border-b p-5 sm:p-7"><label className="mb-3 block text-sm font-bold">What should your story be about?</label><Textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="A curious child finds a paper bird that knows the way to a library beyond the moon…" className="min-h-36 resize-none rounded-2xl bg-[#fcfbfe] p-5 text-base leading-7"/><div className="mt-3 flex flex-wrap gap-2">{ideas.map((p,i)=><button key={p} onClick={()=>setIdea(p)} className="rounded-full border px-3 py-1.5 text-xs text-[#6e687a] hover:border-[#7c65e8]">Try idea {i+1}</button>)}</div></div>
    <div className="grid gap-5 bg-[#faf8fc] p-5 sm:grid-cols-3 sm:p-7"><Picker label="Genre" value={genre} set={setGenre} items={["Magical adventure","Mystery","Comedy","Family memory","Educational quest","Bedtime story"]}/><Picker label="Feeling" value={tone} set={setTone} items={["Wonder-filled","Warm and comforting","Funny and energetic","Mysterious","Inspiring","Gentle and calm"]}/><Picker label="Length" value={duration} set={setDuration} items={["1 minute","3 minutes","5 minutes"]}/></div>
    <div className="flex flex-col justify-between gap-4 border-t p-5 sm:flex-row sm:items-center sm:p-7"><div className="flex flex-wrap gap-5 text-xs text-[#756e82]"><span className="flex gap-1.5"><Film size={15}/>5 scenes</span><span className="flex gap-1.5"><Users size={15}/>Consistent cast</span><span className="flex gap-1.5"><Mic2 size={15}/>Narrated</span></div><Button onClick={create} disabled={loading} className="h-12 rounded-xl bg-[#6246ea] px-6 font-bold hover:bg-[#5235d5]">{loading?<><Loader2 className="animate-spin"/>Building your world…</>:<><WandSparkles/>Create my story</>}</Button></div></div>{notice&&<p className="mt-4 rounded-xl bg-[#fff4e8] px-4 py-3 text-sm text-[#8c572d]">{notice}</p>}</div></TabsContent>
   <TabsContent value="watch">{!story?<Empty onDemo={()=>{setStory(demo);setIndex(0)}}/>:<div className="mx-auto max-w-6xl"><div className="mb-5"><div className="mb-2 flex gap-2"><Badge variant="outline">{story.genre}</Badge><Badge variant="outline">{story.tone}</Badge></div><h1 className="text-3xl font-bold tracking-[-.04em]">{story.title}</h1><p className="mt-2 max-w-2xl text-sm text-[#756f82]">{story.logline}</p></div><div className="grid overflow-hidden rounded-[28px] border bg-[#171427] shadow-[0_26px_80px_rgba(38,27,70,.22)] lg:grid-cols-[1fr_360px]">
    <div className="relative flex min-h-[450px] flex-col justify-end overflow-hidden p-6 text-white sm:min-h-[560px] sm:p-10"><div className="scene-art absolute inset-0"/><div className="absolute inset-0 bg-gradient-to-t from-[#171427] via-[#171427]/25 to-transparent"/><div className="absolute left-6 top-6 flex gap-2 sm:left-10 sm:top-10">{story.characters.map(c=><span key={c.name} title={`${c.name}: ${c.look}`} className="grid size-10 place-items-center rounded-full border-2 border-white/50 text-sm font-bold" style={{backgroundColor:c.color}}>{c.name[0]}</span>)}</div><div className="relative max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-[#d8cdfd]">Scene {index+1} · {scene?.title}</p><p className="text-xl leading-8 sm:text-2xl sm:leading-9">{scene?.narration}</p>{scene?.dialogue&&<blockquote className="mt-5 border-l-2 border-[#f1b660] pl-4 text-lg italic text-[#fff1d6]">“{scene.dialogue}” <span className="ml-2 text-xs not-italic text-white/60">— {scene.character}</span></blockquote>}{scene?.choice&&<div className="mt-6 grid gap-3 sm:grid-cols-2">{scene.choice.map(c=><button key={c.label} onClick={()=>setChoice(c.label)} className={`rounded-xl border p-4 text-left text-sm font-semibold ${choice===c.label?"border-[#f4b95f] bg-[#f4b95f] text-[#282034]":"border-white/30 bg-white/10 hover:bg-white/20"}`}>{c.label}</button>)}</div>}{choice&&scene?.choice&&<p className="mt-3 text-sm text-[#e1daf5]">{scene.choice.find(c=>c.label===choice)?.consequence}</p>}</div></div>
    <aside className="flex flex-col bg-[#fbf9ff] p-5 sm:p-7"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#817a8e]">Visual direction</p><p className="rounded-xl border bg-white p-4 text-sm leading-6 text-[#6f687c]">{scene?.visual}</p>{character&&<div className="mt-6"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#817a8e]">In this scene</p><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full font-bold text-white" style={{backgroundColor:character.color}}>{character.name[0]}</span><div><p className="text-sm font-bold">{character.name}</p><p className="text-xs text-[#766f83]">{character.trait}</p></div></div></div>}<div className="mt-auto pt-8"><Progress value={((index+1)/story.scenes.length)*100} className="mb-5 h-1.5"/><div className="flex justify-between"><Button variant="outline" size="icon" onClick={()=>move(index-1)} disabled={index===0} className="rounded-full"><ChevronLeft/></Button><Button onClick={narrate} className="rounded-full bg-[#6246ea]">{playing?<><Pause/>Pause</>:<><Volume2/>Narrate</>}</Button><Button variant="outline" size="icon" onClick={()=>move(index+1)} disabled={index===story.scenes.length-1} className="rounded-full"><ChevronRight/></Button></div></div></aside></div><div className="mt-5 flex gap-3"><Button variant="outline" onClick={()=>{setIndex(0);setChoice(null)}}><RotateCcw/>Restart</Button><Button variant="outline" onClick={()=>{setIdea(`Continue “${story.title}” after ${choice||"the final scene"}.`);setTab("create")}}><Plus/>Next episode</Button></div></div>}</TabsContent>
   <TabsContent value="library"><div className="mx-auto max-w-5xl"><h1 className="text-4xl font-bold tracking-[-.045em]">Your story worlds</h1><p className="mt-3 mb-7 text-[#756f82]">Stories are saved privately in this browser.</p>{saved.length===0?<Empty onDemo={()=>setTab("create")}/>:<div className="grid gap-4 md:grid-cols-2">{saved.map(s=><button key={s.id} onClick={()=>open(s)} className="rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><Film className="mb-4 text-[#6246ea]"/><h2 className="text-lg font-bold">{s.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#756f82]">{s.logline}</p><div className="mt-4 flex gap-2"><Badge variant="secondary">{s.genre}</Badge><Badge variant="secondary">{s.characters.length} characters</Badge></div></button>)}</div>}</div></TabsContent>
  </Tabs></section></div></main>
}

function Picker({label,value,set,items}:{label:string;value:string;set:(v:string)=>void;items:string[]}){return <div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#7a7487]">{label}</label><Select value={value} onValueChange={v=>v&&set(v)}><SelectTrigger className="h-11 w-full rounded-xl bg-white"><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div>}
function Empty({onDemo}:{onDemo:()=>void}){return <div className="mx-auto max-w-3xl rounded-3xl border border-dashed bg-white p-12 text-center"><CirclePlay className="mx-auto mb-5 size-12 text-[#735bea]"/><h2 className="text-2xl font-bold">Your story world is waiting</h2><p className="mt-3 text-sm text-[#756f82]">Create a world or open the included demonstration.</p><Button onClick={onDemo} className="mt-6 bg-[#6246ea]"><CirclePlay/>Continue</Button></div>}
