const study={auc:{PVMQ:.831,VBQ:.727,CSA:.716,FI:.750,FCSA:.750},non:{PVMQ:.31,VBQ:2.68,CSA:2.65,FI:.43,FCSA:1.52},pjk:{PVMQ:.39,VBQ:3.06,CSA:2.35,FI:.49,FCSA:1.21}};
const avg=a=>a.reduce((s,v)=>s+(Number(v)||0),0)/a.length;
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('activeTab'));document.getElementById(id).classList.add('activeTab');document.querySelectorAll('.navBtn').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));window.scrollTo(0,0)}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>showTab(b.dataset.goto));
function aucHTML(scale=false){return Object.entries(study.auc).map(([k,v])=>`<div class="barRow"><span>${k}</span><div class="barTrack"><div class="barFill" style="width:${scale?Math.max(0,Math.min(100,(v-.5)/.4*100)):v*100}%"></div></div><b>${v.toFixed(3)}</b></div>`).join('')}
document.getElementById('aucChart').innerHTML=aucHTML()+`<small>Apparent AUCs reported in the source cohort; not external validation.</small>`;document.getElementById('evidenceAuc').innerHTML=aucHTML(true);

let demo=false,realFiles=false,manualReady=false,currentKind='none',previewURL=null,currentFiles=[];
const fileInput=document.getElementById('dicomFiles'),filePill=document.getElementById('filePill'),fileStrip=document.getElementById('fileStrip'),fileTitle=document.getElementById('fileTitle'),fileNames=document.getElementById('fileNames'),run=document.getElementById('runAnalysis'),notice=document.getElementById('engineNotice'),viewerShell=document.getElementById('viewerShell'),imageViewer=document.getElementById('imageViewer'),inputBadge=document.getElementById('inputBadge'),viewerFooter=document.getElementById('viewerFooter'),engineTitle=document.getElementById('engineTitle'),engineText=document.getElementById('engineText'),calcPanel=document.getElementById('calcPanel');
function pipeline(id,state,text){const el=document.getElementById(id);el.className='pipeItem '+state;el.querySelector('small').textContent=text}
function ext(name){return (name.split('.').pop()||'').toLowerCase()}
function isRaster(f){return f.type.startsWith('image/')||['jpg','jpeg','png'].includes(ext(f.name))}
function isDicom(f){return f.type==='application/dicom'||ext(f.name)==='dcm'}
function clearPreview(){if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null} imageViewer.innerHTML='<div class="viewerEmpty">Preview available for JPG/PNG. DICOM rendering requires an imaging library/backend.</div>';}
function setAwaitingMeasurements(){manualReady=false;document.getElementById('measureGrid').innerHTML=['PVMQ','VBQ','CSA','FI','FCSA'].map(k=>`<div class="measureBox mutedMeasure"><div><span>${k}</span><span class="pill">Awaiting</span></div><b>—</b><small>${k==='PVMQ'||k==='VBQ'?'requires signal-intensity measurements':'requires segmentation output'}</small></div>`).join('');document.getElementById('phenotype').innerHTML=`<div class="phenotype neutral"><div class="ring"><span>—</span></div><div><span>Status</span><b>Awaiting measurements</b><small>No phenotype is generated from an uploaded image alone.</small></div></div>`;document.getElementById('driverList').innerHTML='<div class="emptyDrivers">Enter independently measured values or load the synthetic demo case.</div>'}
function classifyInput(fs){const raster=fs.filter(isRaster),dicom=fs.filter(isDicom);if(raster.length&&dicom.length)return 'mixed';if(raster.length)return 'screenshot';if(dicom.length)return 'dicom';return 'other'}
function isSyntheticTestStudy(fs){const names=fs.map(f=>f.name.toLowerCase());const req=['sagittal_t1_001.dcm','sagittal_t1_002.dcm','sagittal_t1_003.dcm','axial_t2_l1_l2.dcm','axial_t2_l2_l3.dcm','axial_t2_l3_l4.dcm','axial_t2_l4_l5.dcm','axial_t2_l5_s1.dcm'];return req.every(n=>names.includes(n));}
function loadSyntheticFixture(){document.querySelectorAll('.muscleSI').forEach((x,i)=>x.value=[402,398,406,394][i]);document.querySelectorAll('.vertSI').forEach((x,i)=>x.value=[300,306,311,303][i]);document.getElementById('csfT2').value=1000;document.getElementById('csfT1').value=100;document.getElementById('csa').value=2.32;document.getElementById('fi').value=.50;document.getElementById('fcsa').value=1.18;manualReady=true;updateMeasurements();}
function renderPreview(fs,kind){viewerShell.style.display='block';clearPreview();if(kind==='screenshot' || kind==='mixed'){const f=fs.find(isRaster);previewURL=URL.createObjectURL(f);imageViewer.innerHTML=`<img src="${previewURL}" alt="Uploaded lumbar MRI preview">`;inputBadge.textContent='Screenshot / non-DICOM';inputBadge.className='pill amber';viewerFooter.innerHTML='<span>✓ Visual workflow testing supported</span><span>⚠ Quantitative MRI measurements are not valid from a montage/screenshot without a validated image pipeline.</span>';}else if(kind==='dicom'){inputBadge.textContent='DICOM study';inputBadge.className='pill green';viewerFooter.innerHTML='<span>✓ Preferred quantitative input</span><span>Viewer rendering and automated segmentation require the connected imaging engine.</span>';}else{inputBadge.textContent='Unsupported format';inputBadge.className='pill red';viewerFooter.innerHTML='<span>Use de-identified DICOM, JPG, JPEG or PNG.</span>';}}

fileInput.onchange=()=>{const fs=[...fileInput.files];currentFiles=fs;realFiles=fs.length>0;demo=false;currentKind=classifyInput(fs);if(!realFiles)return;filePill.textContent=`${fs.length} file${fs.length>1?'s':''} loaded`;filePill.className='pill green';fileStrip.style.display='flex';fileTitle.textContent=currentKind==='dicom'?`${fs.length} DICOM object${fs.length>1?'s':''}`:currentKind==='screenshot'?'MRI screenshot / image':currentKind==='mixed'?'Mixed imaging input':'Imaging file';fileNames.textContent=fs.slice(0,5).map(f=>f.name).join(' • ');renderPreview(fs,currentKind);run.disabled=currentKind==='other';pipeline('pIngest','done','Completed');pipeline('pLevel','','Pending');pipeline('pSeg','','Pending');pipeline('pMeasure','','Pending');notice.style.display='none';setAwaitingMeasurements();calcPanel.open=false;};

document.getElementById('loadDemo').onclick=()=>{demo=true;realFiles=false;currentKind='demo';fileInput.value='';filePill.textContent='Demo case loaded';filePill.className='pill green';fileStrip.style.display='flex';fileTitle.textContent='Synthetic demonstration case';fileNames.textContent='No patient imaging is used.';viewerShell.style.display='block';clearPreview();imageViewer.innerHTML='<div class="demoViewer"><div class="demoSpine"></div><div class="demoMuscle dmL"></div><div class="demoMuscle dmR"></div><div class="demoROI d1"></div><div class="demoROI d2"></div><span>AXIAL T2 • SYNTHETIC VISUALIZATION</span></div>';inputBadge.textContent='Synthetic demo';inputBadge.className='pill blue';viewerFooter.innerHTML='<span>Demonstration only — no patient image or inference.</span>';run.disabled=false;pipeline('pIngest','done','Completed');pipeline('pLevel','demo','Demo simulated');pipeline('pSeg','demo','Demo simulated');pipeline('pMeasure','done','Completed');notice.style.display='none';calcPanel.open=true;document.querySelectorAll('.muscleSI').forEach(x=>x.value=390);document.querySelectorAll('.vertSI').forEach(x=>x.value=306);document.getElementById('csfT2').value=1000;document.getElementById('csfT1').value=100;document.getElementById('csa').value=2.35;document.getElementById('fi').value=.49;document.getElementById('fcsa').value=1.21;manualReady=true;updateMeasurements()};

run.onclick=()=>{if(realFiles&&currentKind==='dicom'&&isSyntheticTestStudy(currentFiles)){pipeline('pLevel','done','Synthetic fixture');pipeline('pSeg','demo','Synthetic QC fixture');pipeline('pMeasure','done','Test results generated');notice.style.display='flex';notice.className='notice';engineTitle.textContent='Synthetic test study recognized — end-to-end QC mode completed.';engineText.textContent='These results are fixed synthetic fixture outputs used only to verify ingestion → analysis → results behavior. They are NOT measurements derived from the DICOM pixels and must not be used for clinical or model-performance claims.';calcPanel.open=false;loadSyntheticFixture();document.getElementById('phenotype').insertAdjacentHTML('afterbegin','<div class="syntheticFlag">SYNTHETIC QC RESULT • NOT CLINICAL</div>');return;}if(realFiles){pipeline('pLevel','blocked',currentKind==='screenshot'?'Not reliable from screenshot':'Model needed');pipeline('pSeg','blocked','Model needed');pipeline('pMeasure','manual','Manual / model input');notice.style.display='flex';notice.className='notice warning';calcPanel.open=true;if(currentKind==='screenshot'||currentKind==='mixed'){engineTitle.textContent='Screenshot accepted for prototype review — not quantitative inference.';engineText.textContent='This image can be previewed in the workspace, but PVMQ, VBQ, CSA, FCSA and FI will not be fabricated from a JPG/PNG montage. Use original de-identified DICOM for the future imaging engine, or enter independently measured values below.'}else{engineTitle.textContent='DICOM recognized — imaging engine not connected.';engineText.textContent='The study is accepted, but automated level detection, segmentation and quantitative measurement require the validated imaging backend. You may enter independently measured values below.'}}else if(demo){pipeline('pLevel','demo','Demo simulated');pipeline('pSeg','demo','Demo simulated');pipeline('pMeasure','done','Completed')}};

function values(){const pvmq=avg([...document.querySelectorAll('.muscleSI')].map(x=>x.value))/(Number(document.getElementById('csfT2').value)||1);const vbq=avg([...document.querySelectorAll('.vertSI')].map(x=>x.value))/(Number(document.getElementById('csfT1').value)||1);return {PVMQ:pvmq,VBQ:vbq,CSA:Number(document.getElementById('csa').value)||0,FI:Number(document.getElementById('fi').value)||0,FCSA:Number(document.getElementById('fcsa').value)||0}}
function measure(title,value,label,trend,tone=''){return `<div class="measureBox ${tone}"><div><span>${title}</span><span class="pill ${tone==='danger'?'red':tone==='warn'?'amber':''}">${trend}</span></div><b>${value}</b><small>${label}</small></div>`}
function updateMeasurements(){manualReady=true;const v=values();document.getElementById('measureGrid').innerHTML=measure('PVMQ',v.PVMQ.toFixed(2),'T2 muscle / CSF ratio',v.PVMQ>=study.pjk.PVMQ?'PJK-group direction':'Below PJK-group mean',v.PVMQ>=study.pjk.PVMQ?'danger':'')+measure('VBQ',v.VBQ.toFixed(2),'T1 vertebra / CSF ratio',v.VBQ>=study.pjk.VBQ?'PJK-group direction':'Below PJK-group mean',v.VBQ>=study.pjk.VBQ?'danger':'')+measure('CSA',v.CSA.toFixed(2),'segmentation/manual input',v.CSA<=study.pjk.CSA?'Lower muscle area':'Above PJK-group mean',v.CSA<=study.pjk.CSA?'warn':'')+measure('FI',v.FI.toFixed(2),'segmentation/manual input',v.FI>=study.pjk.FI?'Greater fat infiltration':'Below PJK-group mean',v.FI>=study.pjk.FI?'warn':'')+measure('FCSA',v.FCSA.toFixed(2),'segmentation/manual input',v.FCSA<=study.pjk.FCSA?'Lower functional area':'Above PJK-group mean',v.FCSA<=study.pjk.FCSA?'warn':'');let s=0;if(v.PVMQ>=study.pjk.PVMQ)s+=2;else if(v.PVMQ>study.non.PVMQ)s+=1;if(v.VBQ>=study.pjk.VBQ)s+=2;else if(v.VBQ>study.non.VBQ)s+=1;if(v.FI>=study.pjk.FI)s++;if(v.CSA<=study.pjk.CSA)s++;if(v.FCSA<=study.pjk.FCSA)s++;const ph=s>=6?'Elevated':s>=3?'Intermediate':'Lower',tone=ph==='Elevated'?'danger':ph==='Intermediate'?'warn':'good';document.getElementById('phenotype').innerHTML=`<div class="phenotype ${tone}"><div class="ring"><span>${s}</span><small>/ 7</small></div><div><span>Evidence-direction pattern</span><b>${ph}</b><small>Research display based on source-cohort directions; not an individual PJK probability.</small></div></div>`;const ds=[['PVMQ',v.PVMQ,'0.39',v.PVMQ>=study.pjk.PVMQ],['VBQ',v.VBQ,'3.06',v.VBQ>=study.pjk.VBQ],['Fat infiltration',v.FI,'0.49',v.FI>=study.pjk.FI],['CSA',v.CSA,'2.35',v.CSA<=study.pjk.CSA],['FCSA',v.FCSA,'1.21',v.FCSA<=study.pjk.FCSA]];document.getElementById('driverList').innerHTML=ds.map(d=>`<div class="driver"><div><span>${d[0]}</span><small>PJK-group mean ${d[2]}</small></div><div class="${d[3]?'driverActive':''}">${Number(d[1]).toFixed(2)}</div></div>`).join('')}

document.querySelectorAll('.inputMatrix input').forEach(x=>x.addEventListener('input',updateMeasurements));setAwaitingMeasurements();
